[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo

db_host = dpg-d7l9gun7f7vs73auhebg-a
db_port = 5432
db_user = odoodb_user
db_password = yrJxW7YYqfcX4Aw1tXo3gK9zEd4n182A
db_name = odoodb_b6y6

proxy_mode = True
http_port = 8069
logfile = None
logrotate = False
list_db = False
db_filter = odoodb_b6y6